//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurrence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recurrence()
        {
            this.Purchases = new HashSet<Purchase>();
            this.ServiceRecurrences = new HashSet<ServiceRecurrence>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Option { get; set; }
        public Nullable<decimal> Price_Multiplier { get; set; }
        public Nullable<decimal> Savings { get; set; }
        public Nullable<int> Recurrence_Purchase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual Purchase Purchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRecurrence> ServiceRecurrences { get; set; }
    }
}
