//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecurrence
    {
        public int ServiceID { get; set; }
        public int RecurrenceID { get; set; }
        public string Frequency { get; set; }
        public Nullable<int> PriceMultiplier { get; set; }
    
        public virtual Recurrence Recurrence { get; set; }
        public virtual Service Service { get; set; }
    }
}
